// priority: 300

const EE_STRATAS = {
	stone: {
		name: "stone",
		texture: "minecraft:block/stone",
		fill: "minecraft:stone",
		hardness: 1.5,
		resistance: 6,
		tool: "pickaxe",
	},
	andesite: {
		name: "andesite",
		texture: "minecraft:block/andesite",
		fill: "minecraft:andesite",
		hardness: 1.5,
		resistance: 6,
		tool: "pickaxe",
	},
	diorite: {
		name: "diorite",
		texture: "minecraft:block/diorite",
		fill: "minecraft:diorite",
		hardness: 1.5,
		resistance: 6,
		tool: "pickaxe",
	},
	granite: {
		name: "granite",
		texture: "minecraft:block/granite",
		fill: "minecraft:granite",
		hardness: 1.5,
		resistance: 6,
		tool: "pickaxe",
	},
	deepslate: {
		name: "deepslate",
		texture: "minecraft:block/deepslate",
		fill: "minecraft:deepslate",
		hardness: 3,
		resistance: 6,
		tool: "pickaxe",
	},
	netherrack: {
		name: "netherrack",
		texture: "minecraft:block/netherrack",
		fill: "minecraft:netherrack",
		hardness: 0.4,
		resistance: 0.4,
		tool: "pickaxe",
	},
	end_stone: {
		name: "end_stone",
		texture: "minecraft:block/end_stone",
		fill: "minecraft:end_stone",
		hardness: 3,
		resistance: 9,
		tool: "pickaxe",
	},
};
